### ISSUE TITLE
option to change native fruit and airport color 

### ISSUE THREAD

**Issue by BrandyDerg** [Cuyler36/MyHorizons#31] opened 2020-04-23 11:11 UTC
add the options to change native fruit and airport color in New Horizons would be a lifesaver as I hate my current  fruit/airport color

**Comment by sneedfeedseed** [comment] 2020-04-23 11:58
2nding this, this is a must have

**Comment by umbreon222** [comment] 2020-04-24 17:04
This is a duplicate of #22

**Comment by Cuyler36** [comment] 2020-04-28 09:47
As stated, duplicate of #22.

**Closed as completed by Cuyler36** 2020-04-28 09:47 UTC
